In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [32]:
u = np.linspace(0, 15, 4)
v = np.linspace(0, 3, 4)

a = np.array([])
a2 = np.array([])

for i in range(4):
    a = np.append(a, u[i] - v[i])
    
    a2 = np.append(a2, (u[i] - v[i])**2)
    
print u
print v
print a
print a2

print np.sum(a)
print np.sqrt(np.sum(a2))

[  0.   5.  10.  15.]
[ 0.  1.  2.  3.]
[  0.   4.   8.  12.]
[   0.   16.   64.  144.]
24.0
14.9666295471
