In [229]:
import numpy as np
import sys
import pandas as pd

In [221]:
n = 10

num_inputs = 3

A = 5
B = 8
C = 2

In [222]:
x = np.empty([0,num_inputs-1])

for a in range(n):
    for i in range(n):
        x = np.append(x, [[a, i]], axis=0)
    
x = np.hstack((x, np.ones((n**(num_inputs-1),1))))

In [223]:
def f(x):
    return(A*x[0] + B*x[1])

y = np.array([])

for i in x:
    y = np.append(y, f(i))
    
y = y.reshape(-1, 1)

In [224]:
print x, y

[[ 0.  0.  1.]
 [ 0.  1.  1.]
 [ 0.  2.  1.]
 [ 0.  3.  1.]
 [ 0.  4.  1.]
 [ 0.  5.  1.]
 [ 0.  6.  1.]
 [ 0.  7.  1.]
 [ 0.  8.  1.]
 [ 0.  9.  1.]
 [ 1.  0.  1.]
 [ 1.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  3.  1.]
 [ 1.  4.  1.]
 [ 1.  5.  1.]
 [ 1.  6.  1.]
 [ 1.  7.  1.]
 [ 1.  8.  1.]
 [ 1.  9.  1.]
 [ 2.  0.  1.]
 [ 2.  1.  1.]
 [ 2.  2.  1.]
 [ 2.  3.  1.]
 [ 2.  4.  1.]
 [ 2.  5.  1.]
 [ 2.  6.  1.]
 [ 2.  7.  1.]
 [ 2.  8.  1.]
 [ 2.  9.  1.]
 [ 3.  0.  1.]
 [ 3.  1.  1.]
 [ 3.  2.  1.]
 [ 3.  3.  1.]
 [ 3.  4.  1.]
 [ 3.  5.  1.]
 [ 3.  6.  1.]
 [ 3.  7.  1.]
 [ 3.  8.  1.]
 [ 3.  9.  1.]
 [ 4.  0.  1.]
 [ 4.  1.  1.]
 [ 4.  2.  1.]
 [ 4.  3.  1.]
 [ 4.  4.  1.]
 [ 4.  5.  1.]
 [ 4.  6.  1.]
 [ 4.  7.  1.]
 [ 4.  8.  1.]
 [ 4.  9.  1.]
 [ 5.  0.  1.]
 [ 5.  1.  1.]
 [ 5.  2.  1.]
 [ 5.  3.  1.]
 [ 5.  4.  1.]
 [ 5.  5.  1.]
 [ 5.  6.  1.]
 [ 5.  7.  1.]
 [ 5.  8.  1.]
 [ 5.  9.  1.]
 [ 6.  0.  1.]
 [ 6.  1.  1.]
 [ 6.  2.  1.]
 [ 6.  3.  1.]
 [ 6.  4.  1.]
 [ 6.  5.  1.]
 [ 6.  6. 

In [225]:
lambda_input = int(3)
sigma2_input = float(16)

X_train = x
y_train = y

In [226]:
X_test = np.random.randint(20, size=(n*2, num_inputs-1))
X_test = np.hstack((X_test, np.ones((n*2,1))))
print X_test

[[  3.  14.   1.]
 [  1.  12.   1.]
 [  3.   8.   1.]
 [  2.  13.   1.]
 [  6.  17.   1.]
 [  7.  17.   1.]
 [ 11.   2.   1.]
 [ 10.  14.   1.]
 [ 18.   7.   1.]
 [ 14.  17.   1.]
 [  9.  10.   1.]
 [  2.  16.   1.]
 [  0.  14.   1.]
 [  9.  11.   1.]
 [  3.   6.   1.]
 [ 10.   1.   1.]
 [ 15.   3.   1.]
 [  5.  19.   1.]
 [  5.  16.   1.]
 [ 14.  16.   1.]]


In [258]:
df = pd.DataFrame(x).astype(str)
df = df.applymap(str)

df.to_csv('test.csv', header=False, index=False)

In [227]:
def part1(X, y, lam):
    
    lambda_i = lam*np.identity(num_inputs)
    
    XX = np.matmul(np.transpose(X), X)
    
    XX_recip = np.linalg.matrix_power(lambda_i + XX, -1)
    
    Xy = np.matmul(np.transpose(x), y.reshape(-1,1))
    
    wRR_prediction = np.matmul(XX_recip, Xy)
    
    return wRR_prediction

wRR = part1(X_train, y_train, lambda_input)
np.savetxt("wRR_" + str(lambda_input) + ".csv", wRR, delimiter="\n")

print wRR
print A, B

[[ 4.98482083]
 [ 7.97395126]
 [ 0.18012193]]
5 8


In [228]:
def part2(X, x0):
    
    sigma = sigma2_input**(0.5)
    
    x0 = np.hstack((x0, np.arange(x0[:,0].size).reshape(-1,1)))
    
    def get_index(X, x0):
        
        sigma2_list = np.array([])

        lam_i = lambda_input*np.eye(num_inputs)
        sigm2x = sigma**(-2)*np.transpose(X)
        Sig = np.linalg.matrix_power(lam_i + np.matmul(sigm2x, X),-1)
        
        for i in range(x0[:,0].size):
                        
            sigma20 = sigma2_input + np.matmul(np.matmul(np.transpose(x0[i, 0:-1]), Sig), x0[i, 0:-1])

            sigma2_list = np.append(sigma2_list, sigma20)
    
        return(np.argmax(sigma2_list))
        
    X_known = np.copy(X)
    X_unkown = np.copy(x0)
    
    indexes = np.empty([0, 1])
    
    for a in range(10):
                
        index = get_index(X_known, X_unkown)
                
        X_known = np.append(X_known, X_unkown[index, 0:-1].reshape(1,num_inputs), axis=0)
        
        indexes = np.append(indexes, X_unkown[index, -1])
        
        X_unkown = np.delete(X_unkown, index, 0)
        
    return indexes

active = part2(X_train, X_test)+1

print active
np.savetxt("active_" + str(lambda_input) + "_" + str(int(sigma2_input)) + ".csv", active, delimiter=",") # write output to file

[ 18.   9.  10.  12.  20.  17.  13.   5.   6.  19.]
